# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn clean install dependency:go-offline
      
      # install python and awscli
      - run: 
          name: Install AWS CLI
          command: |
               sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
               curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
               sudo pip install -q awscli --upgrade
               aws --version
               cp /home/circleci/repo/target/PZDemoApp.war /home/circleci/repo/target/PZDemoApp.war_$CIRCLE_BUILD_NUM.zip

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      - store_artifacts:
          path: /home/circleci/repo/target/PZDemoApp.war
          destination: artifact-file
          
      - run: 
          name: Upload to s3
          command: aws s3 cp /home/circleci/repo/target/PZDemoApp.war_$CIRCLE_BUILD_NUM.zip s3://phawsdemo/
        
      # run tests!
      #- run: mvn integration-test
      - run: 
          name: Deploying to Dev
          command: |
            date > date
            echo "Get Application"
            aws deploy get-application --application-name PZDemo --region us-east-2
            echo "Get Deployment Config"
            aws deploy get-deployment-config --deployment-config-name CodeDeployDefault.AllAtOnce --region us-east-2
            echo "Get Deployment Group"
            aws deploy get-deployment-group --application-name PZDemo --deployment-group-name DEV --region us-east-2
            echo "Register Application"
            aws deploy register-application-revision --application-name "PZDemo" --s3-location bucket=phawsdemo,bundleType=zip,key=PZDemoApp.war_$CIRCLE_BUILD_NUM.zip --region us-east-2
            echo "Create Deployment"
            aws deploy create-deployment --application-name PZDemo --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name DEV --s3-location bucket=phawsdemo,bundleType=zip,key=PZDemoApp.war_$CIRCLE_BUILD_NUM.zip --description "Deployed via CircleCI on $(cat date)" --region us-east-2 --file-exists-behavior OVERWRITE > deploy.json
            jq -r '.deploymentId' deploy.json > newdeploy.json
            sed -i '/^null/d' newdeploy.json
                        
      - run: 
          name: Deployment Status
          command: |
            aws deploy wait deployment-successful --deployment-id $(cat newdeploy.json) --region us-east-2   

